<?php

declare(strict_types=1);

// GENERATED from openapi/environment.yaml by bin/generate-management. Do not edit.

namespace Cbox\Id\Client\Management\Environment;

use Cbox\Id\Client\Management\Transport\Danger;
use Cbox\Id\Client\Management\Transport\OperationSpec;
use Cbox\Id\Client\Management\Transport\Pagination;
use InvalidArgumentException;

/**
 * Every operation of the Cbox ID — Environment Management API — method, path, scope, danger and whether it can be
 * held for approval — keyed by action name.
 */
class Operations
{
    /** @var array<string, OperationSpec> */
    private static array $specs = [];

    /** @return list<string> */
    public static function keys(): array
    {
        return [
            'access_reviews.close',
            'access_reviews.create',
            'access_reviews.get',
            'access_reviews.items.decide',
            'access_reviews.items.list',
            'access_reviews.list',
            'action_approvals.get',
            'api_keys.list',
            'api_keys.revoke',
            'apis.create',
            'apis.delete',
            'apis.get',
            'apis.list',
            'apis.scopes.define',
            'apis.scopes.remove',
            'apis.update',
            'approvals.deny',
            'approvals.list',
            'apps.blueprint',
            'apps.copy',
            'apps.create',
            'apps.delete',
            'apps.get',
            'apps.list',
            'apps.manifest.set',
            'apps.manifest.sync',
            'apps.scopes.set',
            'apps.secrets.list',
            'apps.secrets.revoke',
            'apps.secrets.rotate',
            'apps.settings.api_key_prefix',
            'apps.settings.backchannel_logout',
            'apps.settings.token_exchange',
            'apps.settings.token_lifetime',
            'apps.update',
            'audit.list',
            'audit_logs.events.create',
            'audit_logs.events.list',
            'audit_logs.exports.create',
            'audit_logs.exports.get',
            'audit_logs.schemas.create',
            'audit_logs.schemas.delete',
            'audit_logs.schemas.get',
            'audit_logs.schemas.list',
            'audit_logs.schemas.update',
            'audit_logs.settings.get',
            'audit_logs.settings.update',
            'audit_logs.verify',
            'branding.appearance.get',
            'branding.appearance.set',
            'branding.whitelabel.get',
            'branding.whitelabel.set',
            'directories.connect',
            'directories.create',
            'directories.delete',
            'directories.get',
            'directories.groups.list',
            'directories.groups.map',
            'directories.list',
            'directories.status.set',
            'directories.token.rotate',
            'directories.update',
            'domains.add',
            'domains.get',
            'domains.remove',
            'domains.verify',
            'events.list',
            'frontend_keys.create',
            'frontend_keys.list',
            'frontend_keys.revoke',
            'frontend_keys.set_origins',
            'hooks.create',
            'hooks.delete',
            'hooks.get',
            'hooks.list',
            'hooks.update',
            'invitations.list',
            'invitations.resend',
            'invitations.revoke',
            'invitations.send',
            'keys.create',
            'keys.list',
            'keys.revoke',
            'keys.rotate',
            'legacy_login.approve',
            'legacy_login.get',
            'legacy_login.probe',
            'legacy_login.revoke',
            'log_streams.create',
            'log_streams.delete',
            'log_streams.get',
            'log_streams.list',
            'log_streams.test',
            'log_streams.update',
            'members.add',
            'members.list',
            'members.remove',
            'members.roles.grant',
            'members.roles.list',
            'members.roles.revoke',
            'members.update',
            'organizations.create',
            'organizations.delete',
            'organizations.domains.add',
            'organizations.domains.capture',
            'organizations.domains.list',
            'organizations.domains.remove',
            'organizations.domains.verify',
            'organizations.get',
            'organizations.list',
            'organizations.portal_links.create',
            'organizations.portal_links.list',
            'organizations.portal_links.revoke',
            'organizations.reactivate',
            'organizations.suspend',
            'organizations.transfer_ownership',
            'organizations.update',
            'permissions.create',
            'permissions.delete',
            'permissions.list',
            'permissions.update',
            'provisioning.targets.create',
            'provisioning.targets.delete',
            'provisioning.targets.get',
            'provisioning.targets.list',
            'provisioning.targets.status.set',
            'roles.create',
            'roles.delete',
            'roles.get',
            'roles.list',
            'roles.permissions.grant',
            'roles.permissions.revoke',
            'roles.update',
            'saml_apps.create',
            'saml_apps.delete',
            'saml_apps.get',
            'saml_apps.list',
            'saml_apps.update',
            'signin.policy.get',
            'signin.policy.inherit',
            'signin.policy.update',
            'signin.self_service_signup.set',
            'signin.social.delete',
            'signin.social.list',
            'signin.social.set',
            'sod_policies.create',
            'sod_policies.delete',
            'sod_policies.get',
            'sod_policies.list',
            'sod_policies.status.set',
            'sso.connections.activate',
            'sso.connections.certificates.activate',
            'sso.connections.certificates.list',
            'sso.connections.certificates.stage',
            'sso.connections.create',
            'sso.connections.delete',
            'sso.connections.disable',
            'sso.connections.get',
            'sso.connections.list',
            'sso.connections.require_sso',
            'sso.connections.update',
            'sso.domains.capture',
            'sso.domains.create',
            'sso.domains.delete',
            'sso.domains.list',
            'sso.domains.verify',
            'sso.saml_metadata.import',
            'support_sessions.end',
            'support_sessions.start',
            'token_vault.grants.create',
            'token_vault.grants.delete',
            'token_vault.secrets.create',
            'token_vault.secrets.get',
            'token_vault.secrets.list',
            'token_vault.secrets.revoke',
            'token_vault.secrets.rotate',
            'users.create',
            'users.deactivate',
            'users.environment_roles.get',
            'users.environment_roles.grant',
            'users.environment_roles.list',
            'users.environment_roles.revoke',
            'users.erase',
            'users.get',
            'users.list',
            'users.mfa.reset',
            'users.password.set',
            'users.password_reset.send',
            'users.reactivate',
            'users.sessions.list',
            'users.sessions.revoke',
            'users.sessions.revoke_all',
            'users.update',
            'users.verification.send',
            'users.verify',
            'webhooks.create',
            'webhooks.delete',
            'webhooks.get',
            'webhooks.list',
            'webhooks.pause',
            'webhooks.resume',
            'webhooks.secret.rotate',
            'webhooks.signature_scheme.change',
            'webhooks.update',
        ];
    }

    /** @return array<string, OperationSpec> */
    public static function all(): array
    {
        $all = [];

        foreach (self::keys() as $key) {
            $all[$key] = self::spec($key);
        }

        return $all;
    }

    public static function spec(string $key): OperationSpec
    {
        return self::$specs[$key] ??= match ($key) {
            'access_reviews.close' => new OperationSpec(action: 'access_reviews.close', operationId: 'access_reviews_close', method: 'POST', path: '/access-reviews/{id}/close', pathParams: ['id'], scope: 'governance:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'access_reviews.create' => new OperationSpec(action: 'access_reviews.create', operationId: 'access_reviews_create', method: 'POST', path: '/access-reviews', pathParams: [], scope: 'governance:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'access_reviews.get' => new OperationSpec(action: 'access_reviews.get', operationId: 'access_reviews_get', method: 'GET', path: '/access-reviews/{id}', pathParams: ['id'], scope: 'governance:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'access_reviews.items.decide' => new OperationSpec(action: 'access_reviews.items.decide', operationId: 'access_reviews_items_decide', method: 'POST', path: '/access-reviews/{id}/items/{item_id}', pathParams: ['id', 'item_id'], scope: 'governance:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'access_reviews.items.list' => new OperationSpec(action: 'access_reviews.items.list', operationId: 'access_reviews_items_list', method: 'GET', path: '/access-reviews/{id}/items', pathParams: ['id'], scope: 'governance:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'access_reviews.list' => new OperationSpec(action: 'access_reviews.list', operationId: 'access_reviews_list', method: 'GET', path: '/access-reviews', pathParams: [], scope: 'governance:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'action_approvals.get' => new OperationSpec(action: null, operationId: null, method: 'GET', path: '/action-approvals/{id}', pathParams: ['id'], scope: null, danger: null, approval: false, body: false, pagination: null),
            'api_keys.list' => new OperationSpec(action: 'api_keys.list', operationId: 'api_keys_list', method: 'GET', path: '/organizations/{organization_id}/api-keys', pathParams: ['organization_id'], scope: 'api_keys:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'api_keys.revoke' => new OperationSpec(action: 'api_keys.revoke', operationId: 'api_keys_revoke', method: 'DELETE', path: '/api-keys/{id}', pathParams: ['id'], scope: 'api_keys:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'apis.create' => new OperationSpec(action: 'apis.create', operationId: null, method: 'POST', path: '/apis', pathParams: [], scope: 'apis:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apis.delete' => new OperationSpec(action: 'apis.delete', operationId: null, method: 'DELETE', path: '/apis/{id}', pathParams: ['id'], scope: 'apis:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'apis.get' => new OperationSpec(action: 'apis.get', operationId: null, method: 'GET', path: '/apis/{id}', pathParams: ['id'], scope: 'apis:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'apis.list' => new OperationSpec(action: 'apis.list', operationId: null, method: 'GET', path: '/apis', pathParams: [], scope: 'apis:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'apis.scopes.define' => new OperationSpec(action: 'apis.scopes.define', operationId: 'apis_scopes_define', method: 'PUT', path: '/apis/{id}/scopes/{key}', pathParams: ['id', 'key'], scope: 'apis:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apis.scopes.remove' => new OperationSpec(action: 'apis.scopes.remove', operationId: 'apis_scopes_remove', method: 'DELETE', path: '/apis/{id}/scopes/{key}', pathParams: ['id', 'key'], scope: 'apis:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'apis.update' => new OperationSpec(action: 'apis.update', operationId: null, method: 'PATCH', path: '/apis/{id}', pathParams: ['id'], scope: 'apis:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'approvals.deny' => new OperationSpec(action: 'approvals.deny', operationId: 'approvals_deny', method: 'POST', path: '/agent-requests/{request_id}/deny', pathParams: ['request_id'], scope: 'approvals:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'approvals.list' => new OperationSpec(action: 'approvals.list', operationId: 'approvals_list', method: 'GET', path: '/agent-requests', pathParams: [], scope: 'approvals:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'apps.blueprint' => new OperationSpec(action: 'apps.blueprint', operationId: 'apps_blueprint', method: 'GET', path: '/apps/{id}/blueprint', pathParams: ['id'], scope: 'apps:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'apps.copy' => new OperationSpec(action: 'apps.copy', operationId: 'apps_copy', method: 'POST', path: '/apps/{id}/copy', pathParams: ['id'], scope: 'apps:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'apps.create' => new OperationSpec(action: 'apps.create', operationId: 'apps_create', method: 'POST', path: '/apps', pathParams: [], scope: 'apps:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'apps.delete' => new OperationSpec(action: 'apps.delete', operationId: 'apps_delete', method: 'DELETE', path: '/apps/{id}', pathParams: ['id'], scope: 'apps:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'apps.get' => new OperationSpec(action: 'apps.get', operationId: 'apps_get', method: 'GET', path: '/apps/{id}', pathParams: ['id'], scope: 'apps:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'apps.list' => new OperationSpec(action: 'apps.list', operationId: 'apps_list', method: 'GET', path: '/apps', pathParams: [], scope: 'apps:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'apps.manifest.set' => new OperationSpec(action: 'apps.manifest.set', operationId: 'apps_manifest_set', method: 'PUT', path: '/apps/{id}/manifest', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.manifest.sync' => new OperationSpec(action: 'apps.manifest.sync', operationId: 'apps_manifest_sync', method: 'POST', path: '/apps/{id}/manifest/sync', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'apps.scopes.set' => new OperationSpec(action: 'apps.scopes.set', operationId: 'apps_scopes_set', method: 'PUT', path: '/apps/{id}/scopes', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.secrets.list' => new OperationSpec(action: 'apps.secrets.list', operationId: 'apps_secrets_list', method: 'GET', path: '/apps/{id}/secrets', pathParams: ['id'], scope: 'apps:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'apps.secrets.revoke' => new OperationSpec(action: 'apps.secrets.revoke', operationId: 'apps_secrets_revoke', method: 'DELETE', path: '/apps/{id}/secrets/{secret_id}', pathParams: ['id', 'secret_id'], scope: 'apps:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'apps.secrets.rotate' => new OperationSpec(action: 'apps.secrets.rotate', operationId: 'apps_secrets_rotate', method: 'POST', path: '/apps/{id}/secrets', pathParams: ['id'], scope: 'apps:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'apps.settings.api_key_prefix' => new OperationSpec(action: 'apps.settings.api_key_prefix', operationId: 'apps_settings_api_key_prefix', method: 'PUT', path: '/apps/{id}/settings/api-key-prefix', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.settings.backchannel_logout' => new OperationSpec(action: 'apps.settings.backchannel_logout', operationId: 'apps_settings_backchannel_logout', method: 'PUT', path: '/apps/{id}/settings/backchannel-logout', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.settings.token_exchange' => new OperationSpec(action: 'apps.settings.token_exchange', operationId: 'apps_settings_token_exchange', method: 'PUT', path: '/apps/{id}/settings/token-exchange', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.settings.token_lifetime' => new OperationSpec(action: 'apps.settings.token_lifetime', operationId: 'apps_settings_token_lifetime', method: 'PUT', path: '/apps/{id}/settings/token-lifetime', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'apps.update' => new OperationSpec(action: 'apps.update', operationId: 'apps_update', method: 'PATCH', path: '/apps/{id}', pathParams: ['id'], scope: 'apps:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'audit.list' => new OperationSpec(action: 'audit.list', operationId: 'audit_list', method: 'GET', path: '/audit-log', pathParams: [], scope: 'audit:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'audit_logs.events.create' => new OperationSpec(action: 'audit_logs.events.create', operationId: 'audit_logs_events_create', method: 'POST', path: '/audit-logs/events', pathParams: [], scope: 'audit_logs:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'audit_logs.events.list' => new OperationSpec(action: 'audit_logs.events.list', operationId: 'audit_logs_events_list', method: 'GET', path: '/audit-logs/events', pathParams: [], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'audit_logs.exports.create' => new OperationSpec(action: 'audit_logs.exports.create', operationId: 'audit_logs_exports_create', method: 'POST', path: '/audit-logs/exports', pathParams: [], scope: 'audit_logs:export', danger: Danger::Write, approval: true, body: true, pagination: null),
            'audit_logs.exports.get' => new OperationSpec(action: 'audit_logs.exports.get', operationId: 'audit_logs_exports_get', method: 'GET', path: '/audit-logs/exports/{id}', pathParams: ['id'], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'audit_logs.schemas.create' => new OperationSpec(action: 'audit_logs.schemas.create', operationId: 'audit_logs_schemas_create', method: 'POST', path: '/audit-logs/schemas', pathParams: [], scope: 'audit_logs:manage', danger: Danger::Write, approval: true, body: true, pagination: null),
            'audit_logs.schemas.delete' => new OperationSpec(action: 'audit_logs.schemas.delete', operationId: 'audit_logs_schemas_delete', method: 'DELETE', path: '/audit-logs/schemas/{action}', pathParams: ['action'], scope: 'audit_logs:manage', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'audit_logs.schemas.get' => new OperationSpec(action: 'audit_logs.schemas.get', operationId: 'audit_logs_schemas_get', method: 'GET', path: '/audit-logs/schemas/{action}', pathParams: ['action'], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'audit_logs.schemas.list' => new OperationSpec(action: 'audit_logs.schemas.list', operationId: 'audit_logs_schemas_list', method: 'GET', path: '/audit-logs/schemas', pathParams: [], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'audit_logs.schemas.update' => new OperationSpec(action: 'audit_logs.schemas.update', operationId: 'audit_logs_schemas_update', method: 'PUT', path: '/audit-logs/schemas/{action}', pathParams: ['action'], scope: 'audit_logs:manage', danger: Danger::Write, approval: true, body: true, pagination: null),
            'audit_logs.settings.get' => new OperationSpec(action: 'audit_logs.settings.get', operationId: 'audit_logs_settings_get', method: 'GET', path: '/audit-logs/settings', pathParams: [], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'audit_logs.settings.update' => new OperationSpec(action: 'audit_logs.settings.update', operationId: 'audit_logs_settings_update', method: 'PATCH', path: '/audit-logs/settings', pathParams: [], scope: 'audit_logs:manage', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'audit_logs.verify' => new OperationSpec(action: 'audit_logs.verify', operationId: 'audit_logs_verify', method: 'GET', path: '/audit-logs/verify', pathParams: [], scope: 'audit_logs:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'branding.appearance.get' => new OperationSpec(action: 'branding.appearance.get', operationId: 'branding_appearance_get', method: 'GET', path: '/branding/appearance', pathParams: [], scope: 'branding:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'branding.appearance.set' => new OperationSpec(action: 'branding.appearance.set', operationId: 'branding_appearance_set', method: 'PUT', path: '/branding/appearance', pathParams: [], scope: 'branding:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'branding.whitelabel.get' => new OperationSpec(action: 'branding.whitelabel.get', operationId: 'branding_whitelabel_get', method: 'GET', path: '/branding/whitelabel', pathParams: [], scope: 'branding:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'branding.whitelabel.set' => new OperationSpec(action: 'branding.whitelabel.set', operationId: 'branding_whitelabel_set', method: 'PUT', path: '/branding/whitelabel', pathParams: [], scope: 'branding:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'directories.connect' => new OperationSpec(action: 'directories.connect', operationId: 'directories_connect', method: 'POST', path: '/directories/connect', pathParams: [], scope: 'directory_sync:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'directories.create' => new OperationSpec(action: 'directories.create', operationId: 'directories_create', method: 'POST', path: '/directories', pathParams: [], scope: 'directory_sync:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'directories.delete' => new OperationSpec(action: 'directories.delete', operationId: 'directories_delete', method: 'DELETE', path: '/directories/{id}', pathParams: ['id'], scope: 'directory_sync:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'directories.get' => new OperationSpec(action: 'directories.get', operationId: 'directories_get', method: 'GET', path: '/directories/{id}', pathParams: ['id'], scope: 'directory_sync:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'directories.groups.list' => new OperationSpec(action: 'directories.groups.list', operationId: 'directories_groups_list', method: 'GET', path: '/directories/{id}/groups', pathParams: ['id'], scope: 'directory_sync:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'directories.groups.map' => new OperationSpec(action: 'directories.groups.map', operationId: 'directories_groups_map', method: 'POST', path: '/directories/{id}/group-roles', pathParams: ['id'], scope: 'directory_sync:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'directories.list' => new OperationSpec(action: 'directories.list', operationId: 'directories_list', method: 'GET', path: '/directories', pathParams: [], scope: 'directory_sync:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'directories.status.set' => new OperationSpec(action: 'directories.status.set', operationId: 'directories_status_set', method: 'POST', path: '/directories/{id}/status', pathParams: ['id'], scope: 'directory_sync:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'directories.token.rotate' => new OperationSpec(action: 'directories.token.rotate', operationId: 'directories_token_rotate', method: 'POST', path: '/directories/{id}/rotate', pathParams: ['id'], scope: 'directory_sync:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'directories.update' => new OperationSpec(action: 'directories.update', operationId: 'directories_update', method: 'PATCH', path: '/directories/{id}', pathParams: ['id'], scope: 'directory_sync:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'domains.add' => new OperationSpec(action: 'domains.add', operationId: 'domains_add', method: 'POST', path: '/domains', pathParams: [], scope: 'domains:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'domains.get' => new OperationSpec(action: 'domains.get', operationId: 'domains_get', method: 'GET', path: '/domains', pathParams: [], scope: 'domains:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'domains.remove' => new OperationSpec(action: 'domains.remove', operationId: 'domains_remove', method: 'DELETE', path: '/domains', pathParams: [], scope: 'domains:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'domains.verify' => new OperationSpec(action: 'domains.verify', operationId: 'domains_verify', method: 'POST', path: '/domains/verify', pathParams: [], scope: 'domains:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'events.list' => new OperationSpec(action: 'events.list', operationId: 'events_list', method: 'GET', path: '/events', pathParams: [], scope: 'events:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'frontend_keys.create' => new OperationSpec(action: 'frontend_keys.create', operationId: 'frontend_keys_create', method: 'POST', path: '/frontend-keys', pathParams: [], scope: 'frontend_keys:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'frontend_keys.list' => new OperationSpec(action: 'frontend_keys.list', operationId: 'frontend_keys_list', method: 'GET', path: '/frontend-keys', pathParams: [], scope: 'frontend_keys:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'frontend_keys.revoke' => new OperationSpec(action: 'frontend_keys.revoke', operationId: 'frontend_keys_revoke', method: 'DELETE', path: '/frontend-keys/{id}', pathParams: ['id'], scope: 'frontend_keys:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'frontend_keys.set_origins' => new OperationSpec(action: 'frontend_keys.set_origins', operationId: 'frontend_keys_set_origins', method: 'PUT', path: '/frontend-keys/{id}/origins', pathParams: ['id'], scope: 'frontend_keys:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'hooks.create' => new OperationSpec(action: 'hooks.create', operationId: 'hooks_create', method: 'POST', path: '/hooks', pathParams: [], scope: 'hooks:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'hooks.delete' => new OperationSpec(action: 'hooks.delete', operationId: 'hooks_delete', method: 'DELETE', path: '/hooks/{id}', pathParams: ['id'], scope: 'hooks:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'hooks.get' => new OperationSpec(action: 'hooks.get', operationId: 'hooks_get', method: 'GET', path: '/hooks/{id}', pathParams: ['id'], scope: 'hooks:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'hooks.list' => new OperationSpec(action: 'hooks.list', operationId: 'hooks_list', method: 'GET', path: '/hooks', pathParams: [], scope: 'hooks:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'hooks.update' => new OperationSpec(action: 'hooks.update', operationId: 'hooks_update', method: 'PATCH', path: '/hooks/{id}', pathParams: ['id'], scope: 'hooks:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'invitations.list' => new OperationSpec(action: 'invitations.list', operationId: 'invitations_list', method: 'GET', path: '/organizations/{organization_id}/invitations', pathParams: ['organization_id'], scope: 'invitations:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'invitations.resend' => new OperationSpec(action: 'invitations.resend', operationId: 'invitations_resend', method: 'POST', path: '/organizations/{organization_id}/invitations/{invitation_id}/resend', pathParams: ['organization_id', 'invitation_id'], scope: 'invitations:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'invitations.revoke' => new OperationSpec(action: 'invitations.revoke', operationId: 'invitations_revoke', method: 'DELETE', path: '/organizations/{organization_id}/invitations/{invitation_id}', pathParams: ['organization_id', 'invitation_id'], scope: 'invitations:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'invitations.send' => new OperationSpec(action: 'invitations.send', operationId: 'invitations_send', method: 'POST', path: '/organizations/{organization_id}/invitations', pathParams: ['organization_id'], scope: 'invitations:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'keys.create' => new OperationSpec(action: 'keys.create', operationId: 'keys_create', method: 'POST', path: '/keys', pathParams: [], scope: 'keys:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'keys.list' => new OperationSpec(action: 'keys.list', operationId: 'keys_list', method: 'GET', path: '/keys', pathParams: [], scope: 'keys:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'keys.revoke' => new OperationSpec(action: 'keys.revoke', operationId: 'keys_revoke', method: 'DELETE', path: '/keys/{id}', pathParams: ['id'], scope: 'keys:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'keys.rotate' => new OperationSpec(action: 'keys.rotate', operationId: 'keys_rotate', method: 'POST', path: '/keys/{id}/rotate', pathParams: ['id'], scope: 'keys:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'legacy_login.approve' => new OperationSpec(action: 'legacy_login.approve', operationId: 'legacy_login_approve', method: 'POST', path: '/legacy-login/approve', pathParams: [], scope: 'signin:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'legacy_login.get' => new OperationSpec(action: 'legacy_login.get', operationId: 'legacy_login_get', method: 'GET', path: '/legacy-login', pathParams: [], scope: 'signin:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'legacy_login.probe' => new OperationSpec(action: 'legacy_login.probe', operationId: 'legacy_login_probe', method: 'POST', path: '/legacy-login/probe', pathParams: [], scope: 'signin:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'legacy_login.revoke' => new OperationSpec(action: 'legacy_login.revoke', operationId: 'legacy_login_revoke', method: 'POST', path: '/legacy-login/revoke', pathParams: [], scope: 'signin:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'log_streams.create' => new OperationSpec(action: 'log_streams.create', operationId: 'log_streams_create', method: 'POST', path: '/log-streams', pathParams: [], scope: 'log_streams:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'log_streams.delete' => new OperationSpec(action: 'log_streams.delete', operationId: 'log_streams_delete', method: 'DELETE', path: '/log-streams/{id}', pathParams: ['id'], scope: 'log_streams:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'log_streams.get' => new OperationSpec(action: 'log_streams.get', operationId: 'log_streams_get', method: 'GET', path: '/log-streams/{id}', pathParams: ['id'], scope: 'log_streams:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'log_streams.list' => new OperationSpec(action: 'log_streams.list', operationId: 'log_streams_list', method: 'GET', path: '/log-streams', pathParams: [], scope: 'log_streams:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'log_streams.test' => new OperationSpec(action: 'log_streams.test', operationId: 'log_streams_test', method: 'POST', path: '/log-streams/{id}/test', pathParams: ['id'], scope: 'log_streams:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'log_streams.update' => new OperationSpec(action: 'log_streams.update', operationId: 'log_streams_update', method: 'PATCH', path: '/log-streams/{id}', pathParams: ['id'], scope: 'log_streams:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'members.add' => new OperationSpec(action: 'members.add', operationId: 'members_add', method: 'POST', path: '/organizations/{organization_id}/members', pathParams: ['organization_id'], scope: 'members:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'members.list' => new OperationSpec(action: 'members.list', operationId: 'members_list', method: 'GET', path: '/organizations/{organization_id}/members', pathParams: ['organization_id'], scope: 'members:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'members.remove' => new OperationSpec(action: 'members.remove', operationId: 'members_remove', method: 'DELETE', path: '/organizations/{organization_id}/members/{user_id}', pathParams: ['organization_id', 'user_id'], scope: 'members:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'members.roles.grant' => new OperationSpec(action: 'members.roles.grant', operationId: 'members_roles_grant', method: 'PUT', path: '/organizations/{organization_id}/members/{user_id}/roles/{role_id}', pathParams: ['organization_id', 'user_id', 'role_id'], scope: 'roles:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'members.roles.list' => new OperationSpec(action: 'members.roles.list', operationId: 'members_roles_list', method: 'GET', path: '/organizations/{organization_id}/members/{user_id}/roles', pathParams: ['organization_id', 'user_id'], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'members.roles.revoke' => new OperationSpec(action: 'members.roles.revoke', operationId: 'members_roles_revoke', method: 'DELETE', path: '/organizations/{organization_id}/members/{user_id}/roles/{role_id}', pathParams: ['organization_id', 'user_id', 'role_id'], scope: 'roles:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'members.update' => new OperationSpec(action: 'members.update', operationId: 'members_update', method: 'PATCH', path: '/organizations/{organization_id}/members/{user_id}', pathParams: ['organization_id', 'user_id'], scope: 'members:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'organizations.create' => new OperationSpec(action: 'organizations.create', operationId: 'organizations_create', method: 'POST', path: '/organizations', pathParams: [], scope: 'organizations:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'organizations.delete' => new OperationSpec(action: 'organizations.delete', operationId: 'organizations_delete', method: 'DELETE', path: '/organizations/{id}', pathParams: ['id'], scope: 'organizations:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'organizations.domains.add' => new OperationSpec(action: 'organizations.domains.add', operationId: 'organizations_domains_add', method: 'POST', path: '/organizations/{organization_id}/domains', pathParams: ['organization_id'], scope: 'organizations:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'organizations.domains.capture' => new OperationSpec(action: 'organizations.domains.capture', operationId: 'organizations_domains_capture', method: 'PUT', path: '/organizations/{organization_id}/domains/{domain_id}/capture', pathParams: ['organization_id', 'domain_id'], scope: 'organizations:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'organizations.domains.list' => new OperationSpec(action: 'organizations.domains.list', operationId: 'organizations_domains_list', method: 'GET', path: '/organizations/{organization_id}/domains', pathParams: ['organization_id'], scope: 'organizations:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'organizations.domains.remove' => new OperationSpec(action: 'organizations.domains.remove', operationId: 'organizations_domains_remove', method: 'DELETE', path: '/organizations/{organization_id}/domains/{domain_id}', pathParams: ['organization_id', 'domain_id'], scope: 'organizations:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'organizations.domains.verify' => new OperationSpec(action: 'organizations.domains.verify', operationId: 'organizations_domains_verify', method: 'POST', path: '/organizations/{organization_id}/domains/{domain_id}/verify', pathParams: ['organization_id', 'domain_id'], scope: 'organizations:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'organizations.get' => new OperationSpec(action: 'organizations.get', operationId: 'organizations_get', method: 'GET', path: '/organizations/{id}', pathParams: ['id'], scope: 'organizations:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'organizations.list' => new OperationSpec(action: 'organizations.list', operationId: 'organizations_list', method: 'GET', path: '/organizations', pathParams: [], scope: 'organizations:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'organizations.portal_links.create' => new OperationSpec(action: 'organizations.portal_links.create', operationId: 'organizations_portal_links_create', method: 'POST', path: '/organizations/{organization_id}/portal-links', pathParams: ['organization_id'], scope: 'portal_links:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'organizations.portal_links.list' => new OperationSpec(action: 'organizations.portal_links.list', operationId: 'organizations_portal_links_list', method: 'GET', path: '/organizations/{organization_id}/portal-links', pathParams: ['organization_id'], scope: 'portal_links:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'organizations.portal_links.revoke' => new OperationSpec(action: 'organizations.portal_links.revoke', operationId: 'organizations_portal_links_revoke', method: 'DELETE', path: '/organizations/{organization_id}/portal-links/{id}', pathParams: ['organization_id', 'id'], scope: 'portal_links:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'organizations.reactivate' => new OperationSpec(action: 'organizations.reactivate', operationId: 'organizations_reactivate', method: 'POST', path: '/organizations/{id}/reactivate', pathParams: ['id'], scope: 'organizations:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'organizations.suspend' => new OperationSpec(action: 'organizations.suspend', operationId: 'organizations_suspend', method: 'POST', path: '/organizations/{id}/suspend', pathParams: ['id'], scope: 'organizations:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'organizations.transfer_ownership' => new OperationSpec(action: 'organizations.transfer_ownership', operationId: 'organizations_transfer_ownership', method: 'POST', path: '/organizations/{id}/transfer-ownership', pathParams: ['id'], scope: 'organizations:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'organizations.update' => new OperationSpec(action: 'organizations.update', operationId: 'organizations_update', method: 'PATCH', path: '/organizations/{id}', pathParams: ['id'], scope: 'organizations:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'permissions.create' => new OperationSpec(action: 'permissions.create', operationId: 'permissions_create', method: 'POST', path: '/permissions', pathParams: [], scope: 'role_definitions:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'permissions.delete' => new OperationSpec(action: 'permissions.delete', operationId: 'permissions_delete', method: 'DELETE', path: '/permissions/{id}', pathParams: ['id'], scope: 'role_definitions:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'permissions.list' => new OperationSpec(action: 'permissions.list', operationId: 'permissions_list', method: 'GET', path: '/permissions', pathParams: [], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'permissions.update' => new OperationSpec(action: 'permissions.update', operationId: 'permissions_update', method: 'PATCH', path: '/permissions/{id}', pathParams: ['id'], scope: 'role_definitions:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'provisioning.targets.create' => new OperationSpec(action: 'provisioning.targets.create', operationId: 'provisioning_targets_create', method: 'POST', path: '/provisioning-targets', pathParams: [], scope: 'provisioning:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'provisioning.targets.delete' => new OperationSpec(action: 'provisioning.targets.delete', operationId: 'provisioning_targets_delete', method: 'DELETE', path: '/provisioning-targets/{id}', pathParams: ['id'], scope: 'provisioning:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'provisioning.targets.get' => new OperationSpec(action: 'provisioning.targets.get', operationId: 'provisioning_targets_get', method: 'GET', path: '/provisioning-targets/{id}', pathParams: ['id'], scope: 'provisioning:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'provisioning.targets.list' => new OperationSpec(action: 'provisioning.targets.list', operationId: 'provisioning_targets_list', method: 'GET', path: '/provisioning-targets', pathParams: [], scope: 'provisioning:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'provisioning.targets.status.set' => new OperationSpec(action: 'provisioning.targets.status.set', operationId: 'provisioning_targets_status_set', method: 'POST', path: '/provisioning-targets/{id}/status', pathParams: ['id'], scope: 'provisioning:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'roles.create' => new OperationSpec(action: 'roles.create', operationId: 'roles_create', method: 'POST', path: '/roles', pathParams: [], scope: 'role_definitions:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'roles.delete' => new OperationSpec(action: 'roles.delete', operationId: 'roles_delete', method: 'DELETE', path: '/roles/{id}', pathParams: ['id'], scope: 'role_definitions:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'roles.get' => new OperationSpec(action: 'roles.get', operationId: 'roles_get', method: 'GET', path: '/roles/{id}', pathParams: ['id'], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'roles.list' => new OperationSpec(action: 'roles.list', operationId: 'roles_list', method: 'GET', path: '/roles', pathParams: [], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'roles.permissions.grant' => new OperationSpec(action: 'roles.permissions.grant', operationId: 'roles_permissions_grant', method: 'PUT', path: '/roles/{id}/permissions/{permission_id}', pathParams: ['id', 'permission_id'], scope: 'role_definitions:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'roles.permissions.revoke' => new OperationSpec(action: 'roles.permissions.revoke', operationId: 'roles_permissions_revoke', method: 'DELETE', path: '/roles/{id}/permissions/{permission_id}', pathParams: ['id', 'permission_id'], scope: 'role_definitions:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'roles.update' => new OperationSpec(action: 'roles.update', operationId: 'roles_update', method: 'PATCH', path: '/roles/{id}', pathParams: ['id'], scope: 'role_definitions:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'saml_apps.create' => new OperationSpec(action: 'saml_apps.create', operationId: 'saml_apps_create', method: 'POST', path: '/saml-apps', pathParams: [], scope: 'saml_apps:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'saml_apps.delete' => new OperationSpec(action: 'saml_apps.delete', operationId: 'saml_apps_delete', method: 'DELETE', path: '/saml-apps/{id}', pathParams: ['id'], scope: 'saml_apps:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'saml_apps.get' => new OperationSpec(action: 'saml_apps.get', operationId: 'saml_apps_get', method: 'GET', path: '/saml-apps/{id}', pathParams: ['id'], scope: 'saml_apps:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'saml_apps.list' => new OperationSpec(action: 'saml_apps.list', operationId: 'saml_apps_list', method: 'GET', path: '/saml-apps', pathParams: [], scope: 'saml_apps:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'saml_apps.update' => new OperationSpec(action: 'saml_apps.update', operationId: 'saml_apps_update', method: 'PATCH', path: '/saml-apps/{id}', pathParams: ['id'], scope: 'saml_apps:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'signin.policy.get' => new OperationSpec(action: 'signin.policy.get', operationId: 'signin_policy_get', method: 'GET', path: '/sign-in/policy', pathParams: [], scope: 'signin:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'signin.policy.inherit' => new OperationSpec(action: 'signin.policy.inherit', operationId: 'signin_policy_inherit', method: 'DELETE', path: '/sign-in/policy/organizations/{organization_id}', pathParams: ['organization_id'], scope: 'signin:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'signin.policy.update' => new OperationSpec(action: 'signin.policy.update', operationId: 'signin_policy_update', method: 'PATCH', path: '/sign-in/policy', pathParams: [], scope: 'signin:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'signin.self_service_signup.set' => new OperationSpec(action: 'signin.self_service_signup.set', operationId: 'signin_self_service_signup_set', method: 'PUT', path: '/sign-in/self-service-signup', pathParams: [], scope: 'signin:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'signin.social.delete' => new OperationSpec(action: 'signin.social.delete', operationId: 'signin_social_delete', method: 'DELETE', path: '/sign-in/social-providers/{id}', pathParams: ['id'], scope: 'signin:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'signin.social.list' => new OperationSpec(action: 'signin.social.list', operationId: 'signin_social_list', method: 'GET', path: '/sign-in/social-providers', pathParams: [], scope: 'signin:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'signin.social.set' => new OperationSpec(action: 'signin.social.set', operationId: 'signin_social_set', method: 'POST', path: '/sign-in/social-providers', pathParams: [], scope: 'signin:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sod_policies.create' => new OperationSpec(action: 'sod_policies.create', operationId: 'sod_policies_create', method: 'POST', path: '/sod-policies', pathParams: [], scope: 'governance:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'sod_policies.delete' => new OperationSpec(action: 'sod_policies.delete', operationId: 'sod_policies_delete', method: 'DELETE', path: '/sod-policies/{id}', pathParams: ['id'], scope: 'governance:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sod_policies.get' => new OperationSpec(action: 'sod_policies.get', operationId: 'sod_policies_get', method: 'GET', path: '/sod-policies/{id}', pathParams: ['id'], scope: 'governance:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'sod_policies.list' => new OperationSpec(action: 'sod_policies.list', operationId: 'sod_policies_list', method: 'GET', path: '/sod-policies', pathParams: [], scope: 'governance:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'sod_policies.status.set' => new OperationSpec(action: 'sod_policies.status.set', operationId: 'sod_policies_status_set', method: 'POST', path: '/sod-policies/{id}/status', pathParams: ['id'], scope: 'governance:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.activate' => new OperationSpec(action: 'sso.connections.activate', operationId: 'sso_connections_activate', method: 'POST', path: '/sso/connections/{id}/activate', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.certificates.activate' => new OperationSpec(action: 'sso.connections.certificates.activate', operationId: 'sso_connections_certificates_activate', method: 'POST', path: '/sso/connections/{id}/certificates/activate', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.certificates.list' => new OperationSpec(action: 'sso.connections.certificates.list', operationId: 'sso_connections_certificates_list', method: 'GET', path: '/sso/connections/{id}/certificates', pathParams: ['id'], scope: 'sso:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'sso.connections.certificates.stage' => new OperationSpec(action: 'sso.connections.certificates.stage', operationId: 'sso_connections_certificates_stage', method: 'POST', path: '/sso/connections/{id}/certificates', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.create' => new OperationSpec(action: 'sso.connections.create', operationId: 'sso_connections_create', method: 'POST', path: '/sso/connections', pathParams: [], scope: 'sso:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'sso.connections.delete' => new OperationSpec(action: 'sso.connections.delete', operationId: 'sso_connections_delete', method: 'DELETE', path: '/sso/connections/{id}', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.disable' => new OperationSpec(action: 'sso.connections.disable', operationId: 'sso_connections_disable', method: 'POST', path: '/sso/connections/{id}/disable', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.get' => new OperationSpec(action: 'sso.connections.get', operationId: 'sso_connections_get', method: 'GET', path: '/sso/connections/{id}', pathParams: ['id'], scope: 'sso:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'sso.connections.list' => new OperationSpec(action: 'sso.connections.list', operationId: 'sso_connections_list', method: 'GET', path: '/sso/connections', pathParams: [], scope: 'sso:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'sso.connections.require_sso' => new OperationSpec(action: 'sso.connections.require_sso', operationId: 'sso_connections_require_sso', method: 'POST', path: '/sso/connections/{id}/require-sso', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.connections.update' => new OperationSpec(action: 'sso.connections.update', operationId: 'sso_connections_update', method: 'PATCH', path: '/sso/connections/{id}', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.domains.capture' => new OperationSpec(action: 'sso.domains.capture', operationId: 'sso_domains_capture', method: 'POST', path: '/sso/domains/{id}/capture', pathParams: ['id'], scope: 'sso:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'sso.domains.create' => new OperationSpec(action: 'sso.domains.create', operationId: 'sso_domains_create', method: 'POST', path: '/sso/domains', pathParams: [], scope: 'sso:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'sso.domains.delete' => new OperationSpec(action: 'sso.domains.delete', operationId: 'sso_domains_delete', method: 'DELETE', path: '/sso/domains/{id}', pathParams: ['id'], scope: 'sso:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'sso.domains.list' => new OperationSpec(action: 'sso.domains.list', operationId: 'sso_domains_list', method: 'GET', path: '/sso/domains', pathParams: [], scope: 'sso:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'sso.domains.verify' => new OperationSpec(action: 'sso.domains.verify', operationId: 'sso_domains_verify', method: 'POST', path: '/sso/domains/{id}/verify', pathParams: ['id'], scope: 'sso:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'sso.saml_metadata.import' => new OperationSpec(action: 'sso.saml_metadata.import', operationId: 'sso_saml_metadata_import', method: 'POST', path: '/sso/saml-metadata', pathParams: [], scope: 'sso:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'support_sessions.end' => new OperationSpec(action: 'support_sessions.end', operationId: 'support_sessions_end', method: 'DELETE', path: '/support-sessions/{id}', pathParams: ['id'], scope: 'support:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'support_sessions.start' => new OperationSpec(action: 'support_sessions.start', operationId: 'support_sessions_start', method: 'POST', path: '/support-sessions', pathParams: [], scope: 'support:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'token_vault.grants.create' => new OperationSpec(action: 'token_vault.grants.create', operationId: 'token_vault_grants_create', method: 'POST', path: '/token-vault/secrets/{id}/grants', pathParams: ['id'], scope: 'token_vault:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'token_vault.grants.delete' => new OperationSpec(action: 'token_vault.grants.delete', operationId: 'token_vault_grants_delete', method: 'DELETE', path: '/token-vault/secrets/{id}/grants/{client_id}', pathParams: ['id', 'client_id'], scope: 'token_vault:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'token_vault.secrets.create' => new OperationSpec(action: 'token_vault.secrets.create', operationId: 'token_vault_secrets_create', method: 'POST', path: '/token-vault/secrets', pathParams: [], scope: 'token_vault:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'token_vault.secrets.get' => new OperationSpec(action: 'token_vault.secrets.get', operationId: 'token_vault_secrets_get', method: 'GET', path: '/token-vault/secrets/{id}', pathParams: ['id'], scope: 'token_vault:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'token_vault.secrets.list' => new OperationSpec(action: 'token_vault.secrets.list', operationId: 'token_vault_secrets_list', method: 'GET', path: '/token-vault/secrets', pathParams: [], scope: 'token_vault:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'token_vault.secrets.revoke' => new OperationSpec(action: 'token_vault.secrets.revoke', operationId: 'token_vault_secrets_revoke', method: 'POST', path: '/token-vault/secrets/{id}/revoke', pathParams: ['id'], scope: 'token_vault:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'token_vault.secrets.rotate' => new OperationSpec(action: 'token_vault.secrets.rotate', operationId: 'token_vault_secrets_rotate', method: 'POST', path: '/token-vault/secrets/{id}/rotate', pathParams: ['id'], scope: 'token_vault:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'users.create' => new OperationSpec(action: 'users.create', operationId: 'users_create', method: 'POST', path: '/users', pathParams: [], scope: 'users:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            'users.deactivate' => new OperationSpec(action: 'users.deactivate', operationId: 'users_deactivate', method: 'DELETE', path: '/users/{id}', pathParams: ['id'], scope: 'users:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'users.environment_roles.get' => new OperationSpec(action: 'users.environment_roles.get', operationId: 'users_environment_roles_get', method: 'GET', path: '/users/{id}/environment-roles/{role_id}', pathParams: ['id', 'role_id'], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'users.environment_roles.grant' => new OperationSpec(action: 'users.environment_roles.grant', operationId: 'users_environment_roles_grant', method: 'PUT', path: '/users/{id}/environment-roles/{role_id}', pathParams: ['id', 'role_id'], scope: 'roles:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'users.environment_roles.list' => new OperationSpec(action: 'users.environment_roles.list', operationId: 'users_environment_roles_list', method: 'GET', path: '/users/{id}/environment-roles', pathParams: ['id'], scope: 'roles:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'users.environment_roles.revoke' => new OperationSpec(action: 'users.environment_roles.revoke', operationId: 'users_environment_roles_revoke', method: 'DELETE', path: '/users/{id}/environment-roles/{role_id}', pathParams: ['id', 'role_id'], scope: 'roles:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'users.erase' => new OperationSpec(action: 'users.erase', operationId: 'users_erase', method: 'POST', path: '/users/{id}/erase', pathParams: ['id'], scope: 'users:erase', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'users.get' => new OperationSpec(action: 'users.get', operationId: 'users_get', method: 'GET', path: '/users/{id}', pathParams: ['id'], scope: 'users:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'users.list' => new OperationSpec(action: 'users.list', operationId: 'users_list', method: 'GET', path: '/users', pathParams: [], scope: 'users:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'users.mfa.reset' => new OperationSpec(action: 'users.mfa.reset', operationId: 'users_mfa_reset', method: 'DELETE', path: '/users/{id}/mfa', pathParams: ['id'], scope: 'users:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'users.password.set' => new OperationSpec(action: 'users.password.set', operationId: 'users_password_set', method: 'POST', path: '/users/{id}/password', pathParams: ['id'], scope: 'users:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'users.password_reset.send' => new OperationSpec(action: 'users.password_reset.send', operationId: 'users_password_reset_send', method: 'POST', path: '/users/{id}/password-reset', pathParams: ['id'], scope: 'users:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'users.reactivate' => new OperationSpec(action: 'users.reactivate', operationId: 'users_reactivate', method: 'POST', path: '/users/{id}/reactivate', pathParams: ['id'], scope: 'users:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'users.sessions.list' => new OperationSpec(action: 'users.sessions.list', operationId: 'users_sessions_list', method: 'GET', path: '/users/{id}/sessions', pathParams: ['id'], scope: 'users:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'users.sessions.revoke' => new OperationSpec(action: 'users.sessions.revoke', operationId: 'users_sessions_revoke', method: 'DELETE', path: '/users/{id}/sessions/{session_id}', pathParams: ['id', 'session_id'], scope: 'users:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'users.sessions.revoke_all' => new OperationSpec(action: 'users.sessions.revoke_all', operationId: 'users_sessions_revoke_all', method: 'DELETE', path: '/users/{id}/sessions', pathParams: ['id'], scope: 'users:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'users.update' => new OperationSpec(action: 'users.update', operationId: 'users_update', method: 'PATCH', path: '/users/{id}', pathParams: ['id'], scope: 'users:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'users.verification.send' => new OperationSpec(action: 'users.verification.send', operationId: 'users_verification_send', method: 'POST', path: '/users/{id}/verification', pathParams: ['id'], scope: 'users:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'users.verify' => new OperationSpec(action: 'users.verify', operationId: 'users_verify', method: 'POST', path: '/users/{id}/verify', pathParams: ['id'], scope: 'users:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'webhooks.create' => new OperationSpec(action: 'webhooks.create', operationId: 'webhooks_create', method: 'POST', path: '/webhooks', pathParams: [], scope: 'webhooks:write', danger: Danger::Critical, approval: true, body: true, pagination: null),
            'webhooks.delete' => new OperationSpec(action: 'webhooks.delete', operationId: 'webhooks_delete', method: 'DELETE', path: '/webhooks/{id}', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Destructive, approval: true, body: false, pagination: null),
            'webhooks.get' => new OperationSpec(action: 'webhooks.get', operationId: 'webhooks_get', method: 'GET', path: '/webhooks/{id}', pathParams: ['id'], scope: 'webhooks:read', danger: Danger::Read, approval: true, body: false, pagination: null),
            'webhooks.list' => new OperationSpec(action: 'webhooks.list', operationId: 'webhooks_list', method: 'GET', path: '/webhooks', pathParams: [], scope: 'webhooks:read', danger: Danger::Read, approval: true, body: false, pagination: Pagination::Cursor),
            'webhooks.pause' => new OperationSpec(action: 'webhooks.pause', operationId: 'webhooks_pause', method: 'POST', path: '/webhooks/{id}/pause', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'webhooks.resume' => new OperationSpec(action: 'webhooks.resume', operationId: 'webhooks_resume', method: 'POST', path: '/webhooks/{id}/resume', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Write, approval: true, body: false, pagination: null),
            'webhooks.secret.rotate' => new OperationSpec(action: 'webhooks.secret.rotate', operationId: 'webhooks_secret_rotate', method: 'POST', path: '/webhooks/{id}/rotate', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Critical, approval: true, body: false, pagination: null),
            'webhooks.signature_scheme.change' => new OperationSpec(action: 'webhooks.signature_scheme.change', operationId: 'webhooks_signature_scheme_change', method: 'POST', path: '/webhooks/{id}/signature-scheme', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Destructive, approval: true, body: true, pagination: null),
            'webhooks.update' => new OperationSpec(action: 'webhooks.update', operationId: 'webhooks_update', method: 'PATCH', path: '/webhooks/{id}', pathParams: ['id'], scope: 'webhooks:write', danger: Danger::Write, approval: true, body: true, pagination: null),
            default => throw new InvalidArgumentException("No environment operation is keyed {$key}."),
        };
    }
}
